config/routes.rb
Rails.application.routes.draw do
  resources :monsters
  resources :players
  root to: 'game#menu'
  
  get 'players/:id/up', to: 'players#up', as: 'player_up'
  get 'players/:id/down', to: 'players#down', as: 'player_down'
  get 'players/:id/left', to: 'players#left', as: 'player_left'
  get 'players/:id/right', to: 'players#right', as: 'player_right'

  get 'map/:id', to: 'game#map', as: 'game_map'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def map
    @players = Player.all;
    @monsters = Monster.all;
    @player = Player.find(params[:id])
    
    @map = Array.new(11){ Array.new(11) }
    @players.each do |player|
      @map[player.y_pos][player.x_pos] = "player"
    end
    @monsters.each do |monster|
      @map[monster.y_pos][monster.x_pos] = "monster"
    end
  end

  def menu
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :x_pos, :y_pos, :health)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy, :up, :down, :left, :right]

  def up
    @player.y_pos -= 1;
    @player.save;
    MapBroadcastJob.perform_later
    respond_to do |format|
      format.html { redirect_to game_map_path }
      format.json { render :show, status: :ok, location: @player }
    end
  end
  
  def down
    @player.y_pos += 1;
    @player.save;
    MapBroadcastJob.perform_later
    respond_to do |format|
      format.html { redirect_to game_map_path }
      format.json { render :show, status: :ok, location: @player }
    end
  end
  
  def left
    @player.x_pos -= 1;
    @player.save;
    MapBroadcastJob.perform_later
    respond_to do |format|
      format.html { redirect_to game_map_path }
      format.json { render :show, status: :ok, location: @player }
    end
  end
  
  def right
    @player.x_pos += 1;
    @player.save;
    MapBroadcastJob.perform_later
    respond_to do |format|
      format.html { redirect_to game_map_path }
      format.json { render :show, status: :ok, location: @player }
    end
  end

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :x_pos, :y_pos, :health)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/game/map.html.erb
<table id="map" class="map">
  <% 11.times do |row| %>
  <tr>
    <% 11.times do |column| %>
    <td class="<%= @map[row][column] %>"></td>
    <% end %>
  </tr>
  <% end %>
</table>
<div style="display:none;">
  <%= link_to 'Up', player_up_path(@player), id: "up" %>
  <%= link_to 'Down', player_down_path(@player), id: "down" %>
  <%= link_to 'Left', player_left_path(@player), id: "left" %>
  <%= link_to 'Right', player_right_path(@player), id: "right" %>
</div>

app/views/game/menu.html.erb
<h1>Game#menu</h1>
<p>Find me in app/views/game/menu.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RPG</title>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_with(model: monster, local: true) do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :monster_name %>
  </div>

  <div class="field">
    <%= form.label :x_pos %>
    <%= form.number_field :x_pos, id: :monster_x_pos %>
  </div>

  <div class="field">
    <%= form.label :y_pos %>
    <%= form.number_field :y_pos, id: :monster_y_pos %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health, id: :monster_health %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>X pos</th>
      <th>Y pos</th>
      <th>Health</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.x_pos %></td>
        <td><%= monster.y_pos %></td>
        <td><%= monster.health %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>X pos:</strong>
  <%= @monster.x_pos %>
</p>

<p>
  <strong>Y pos:</strong>
  <%= @monster.y_pos %>
</p>

<p>
  <strong>Health:</strong>
  <%= @monster.health %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :player_name %>
  </div>

  <div class="field">
    <%= form.label :x_pos %>
    <%= form.number_field :x_pos, id: :player_x_pos %>
  </div>

  <div class="field">
    <%= form.label :y_pos %>
    <%= form.number_field :y_pos, id: :player_y_pos %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health, id: :player_health %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>X pos</th>
      <th>Y pos</th>
      <th>Health</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.x_pos %></td>
        <td><%= player.y_pos %></td>
        <td><%= player.health %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>X pos:</strong>
  <%= @player.x_pos %>
</p>

<p>
  <strong>Y pos:</strong>
  <%= @player.y_pos %>
</p>

<p>
  <strong>Health:</strong>
  <%= @player.health %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>